name: time_planner_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  go_router: ^14.1.4
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  equatable: ^2.0.5
  dio: ^5.4.3+1
  jwt_decoder: ^2.0.1
  bloc: ^8.1.4
  rxdart: ^0.27.7
  intl: ^0.19.0
  calendar_view: ^1.2.0
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/background.png
    - assets/background2.png
    
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/AvenirNextCyr-Heavy.ttf
        
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Bold.ttf

  uses-material-design: true

